import { Link } from "react-router-dom";
import { categDt } from "../../assets/data";


export default function Categories(){
    return(
        <div className='home-section categories-container'>
            <div className="home-section-heading text-center">
                <h1>We stock a wide range of products</h1>
                <p>
                    We stocks a wide range of items, from gently used electronics, clothing to books, household items, toys and more.
                </p>
            </div>
            <div className="home-section-content categories-content">
                {categDt.map((category, index) => (
                    <Link className="category-card" style={{backgroundImage:`url(${category.image})`}} key={index} to={`/products/${category.url}`}>
                        <div className='category-card-text'>{category.text}</div>
                    </Link>
                ))}
            </div>
        </div>
    )
}

/*

Shop, Save, Support Online!
Shop the Mission Store online to help individuals & families struggling with hunger, homelessness, poverty, mental illness, & addiction. Net proceeds from the Mission Store support Mission Services of London's branches of service: Men's Mission, Rotholme Family Shelter, Quintin Warner House, Community Mental Health Programs, 

& the Mission Store's outreach programs.

Shop Mission Store on eBayShop Mission Store on Poshmark
There are many great reasons to shop our online storefronts:
Yellow heart
Help The Most Vulnerable


Prevent Reusable Items From Ending Up In A Landfill

Net revenue generated by the merchandise we sell is used to fund Mission Services of London’s important and life-changing programs. Click here to learn more.

All clothing and other household items donated to the Mission Store are either sold in store to raise vital funds, or given to struggling individuals and families at no cost to them. If they cannot be sold or given away, they are sent through a waste diversion stream to be recycled or reused, whenever possible.

wallet
Save Money


Find Something Unique

At the Mission Store, you can find quality products at affordable prices, even on a limited budget.

Look through our large inventory of products and find something unique and useful.

Our online thrift store via Poshmark sells a variety of lightly used items. You can find children's clothes, women's and men's clothes as well as vintage styles, shoes and accessories among our listings.

Great finds await you on eBay. You'll find interesting & vintage household items, accessories, toys, books, & more.


Shop Mission Store on eBayShop Mission Store on Poshmark





We stock a wide range of products
The Mission Store stocks a wide range of items, from gently used clothing to books, household items, electronics, toys and more.



Women's Clothing And Accessories
Antiques
Men's Clothing
Sporting Goods
Books
Jewellery & Watches
Home & Kitchen
Children's Clothing
Collectibles
Toys & Hobbies


Visit our online stores now
Mission Store is a branch of Mission Services of London, in Ontario, Canada. Our Mission is to actively respond to people experiencing need, affirm human dignity and inspire hope. All net proceeds of items sold in the store and online support people in need through community programs.

Shop Mission Store on eBayShop Mission Store on Poshmark


*/